# Generated by Django 6.1.1 on 2026-10-05 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        ('tenants', '0002_tenant_allow_negative_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alert when stock falls to this quantity or below.', max_digits=14, verbose_name='low-stock level'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Turn off for services or things you do not count.', verbose_name='track stock'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for stock coming in; used to value stock.', max_digits=14, null=True)),
                ('kind', models.CharField(choices=[('opening', 'Opening stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('adjust_in', 'Stock added'), ('adjust_out', 'Stock removed'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('transfer_ref', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to='erp.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='erp.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='erp.warehouse')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Where the stock comes from / goes to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_warehouse_name'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'product', 'date'], name='erp_stockmo_tenant__afbbc4_idx'),
        ),
    ]
