# Generated by Django 6.1.1 on 2026-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_negative_stock',
            field=models.BooleanField(default=True, help_text='If off, a sale that would take stock below zero is blocked. If on, it is allowed with a warning.'),
        ),
    ]
